export const Fonts = {
    font_free: "font-free",
    kepler_regular: "kepler-regular",
    kepler_medium: "kepler-medium",
    kepler_light_italic: "kepler-light-italic",
    kepler_light: "kepler-light",
    kepler_bold: "kepler-bold",
    whitney_bold: "whitney-bold",
    whitney_book: "whitney-book",
    whitney_book_italic: "whitney-book-italic",
    whitney_light: "whitney-light",
    whitney_light_italic: "whitney-light-italic",
    whitney_medium: "whitney-medium",
    whitney_medium_italic: "whitney-medium-italic",
    whitney_semi_bold: "whitney-semi-bold",
    whitney_semi_bold_italic: "whitney-semi-bold-italic",
    open_sans_condensed_bold: "open-sans-condensed-bold",
    open_sans_condensed_regular: "open-sans-condensed-regular",
    open_sans_condensed_semi_bold: "open-sans-condensed-semi-bold",
    open_sans_bold: "open-sans-bold",
    open_sans_semi_bold: "open-sans-semi-bold",
    open_sans_regular: "open-sans-regular"
  }